app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

api_posts:
    resource: "@AppBundle/Controller/PostController.php"
    type: rest
    prefix: /api

api_comments:
    resource: "@AppBundle/Controller/CommentController.php"
    type: rest
    prefix: /api/posts/{postId}
