<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AppRepository
{
    /**
     * テストデータ投入用関数
     * 既存のエンティティを返す
     */
    public function getCategories($slugs = array())
    {
        $entities = array();
        if ($slugs) {
            $entities = $this->findBySlug($slugs);
        }

        if (empty($entities)) {
            $count = count($this->findAll());
            $entities = $this->createQueryBuilder('r')
                ->setFirstResult(rand(0, $count - 1))
                ->setMaxResults(1)
                ->getQuery()
                ->getResult();
        }

        return $entities;
    }
}
